name: Bug Report
description: Reportar un bug o comportamiento inesperado
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Gracias por reportar un bug. Por favor completa las secciones a continuacion.

  - type: textarea
    id: description
    attributes:
      label: Descripcion del Bug
      description: Descripcion clara y concisa del bug
      placeholder: Que sucedio?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Pasos para Reproducir
      description: Pasos para reproducir el comportamiento
      placeholder: |
        1. Ir a '...'
        2. Ejecutar '...'
        3. Ver error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamiento Esperado
      description: Que esperabas que sucediera?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamiento Actual
      description: Que sucedio realmente?
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Que version estas ejecutando?
      options:
        - v1.0.0
        - main branch
        - Otra (especificar en descripcion)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Sistema Operativo
      options:
        - Windows
        - macOS
        - Linux
        - Docker
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs Relevantes
      description: Pega cualquier log relevante
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: He buscado issues existentes para evitar duplicados
          required: true
        - label: He incluido toda la informacion relevante
          required: true
