// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Observa.Infrastructure.Persistence;

#nullable disable

namespace Observa.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ObservaDbContext))]
    [Migration("20260209212812_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Observa.Domain.Aggregates.Dashboard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("dashboards", (string)null);
                });

            modelBuilder.Entity("Observa.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid>("DashboardId")
                        .HasColumnType("uuid")
                        .HasColumnName("dashboard_id");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("boolean")
                        .HasColumnName("is_acknowledged");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.HasKey("Id");

                    b.HasIndex("DashboardId")
                        .HasDatabaseName("ix_alerts_dashboard_id");

                    b.HasIndex("IsAcknowledged")
                        .HasDatabaseName("ix_alerts_is_acknowledged");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("Observa.Domain.Entities.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("connection_string");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("data_sources", (string)null);
                });

            modelBuilder.Entity("Observa.Domain.Entities.Widget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<string>("RefreshInterval")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("refresh_interval");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("dashboard_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("dashboard_id");

                    b.ToTable("widgets", (string)null);
                });

            modelBuilder.Entity("Observa.Domain.Aggregates.Dashboard", b =>
                {
                    b.OwnsMany("Observa.Domain.ValueObjects.ThresholdRule", "ThresholdRules", b1 =>
                        {
                            b1.Property<Guid>("DashboardId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("MetricName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("metric_name");

                            b1.Property<string>("Operator")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("operator");

                            b1.Property<string>("Severity")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("severity");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("value");

                            b1.HasKey("DashboardId", "Id");

                            b1.ToTable("dashboard_threshold_rules", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DashboardId");
                        });

                    b.Navigation("ThresholdRules");
                });

            modelBuilder.Entity("Observa.Domain.Entities.Alert", b =>
                {
                    b.OwnsOne("Observa.Domain.ValueObjects.ThresholdRule", "Rule", b1 =>
                        {
                            b1.Property<Guid>("AlertId")
                                .HasColumnType("uuid");

                            b1.Property<string>("MetricName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("rule_metric_name");

                            b1.Property<string>("Operator")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("rule_operator");

                            b1.Property<string>("Severity")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("rule_severity");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("rule_value");

                            b1.HasKey("AlertId");

                            b1.ToTable("alerts");

                            b1.WithOwner()
                                .HasForeignKey("AlertId");
                        });

                    b.Navigation("Rule")
                        .IsRequired();
                });

            modelBuilder.Entity("Observa.Domain.Entities.Widget", b =>
                {
                    b.HasOne("Observa.Domain.Aggregates.Dashboard", null)
                        .WithMany("Widgets")
                        .HasForeignKey("dashboard_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Observa.Domain.ValueObjects.WidgetPosition", "Position", b1 =>
                        {
                            b1.Property<Guid>("WidgetId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Column")
                                .HasColumnType("integer")
                                .HasColumnName("position_column");

                            b1.Property<int>("Height")
                                .HasColumnType("integer")
                                .HasColumnName("position_height");

                            b1.Property<int>("Row")
                                .HasColumnType("integer")
                                .HasColumnName("position_row");

                            b1.Property<int>("Width")
                                .HasColumnType("integer")
                                .HasColumnName("position_width");

                            b1.HasKey("WidgetId");

                            b1.ToTable("widgets");

                            b1.WithOwner()
                                .HasForeignKey("WidgetId");
                        });

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("Observa.Domain.Aggregates.Dashboard", b =>
                {
                    b.Navigation("Widgets");
                });
#pragma warning restore 612, 618
        }
    }
}
